import type { Car, Circuit, Driver, NewsItem, Race, Team } from "./types";
import { raceStatusFor } from "./race-status";

export const CURRENT_SEASON = 2026;
export const CURRENT_SNAPSHOT_VERIFIED_AT = "2026-08-08T00:00:00Z";
export const AVAILABLE_SEASONS = Array.from({ length: 77 }, (_, index) => 2026 - index);

export const teams: Team[] = [
  {
    id: "mercedes",
    name: "Mercedes",
    shortName: "Mercedes",
    color: "#00a19b",
    base: { zh: "英国布拉克利", en: "Brackley, United Kingdom" },
    principal: "Toto Wolff",
    firstEntry: 1954,
    championships: 8,
    points: 379,
    position: 1,
    drivers: ["antonelli", "russell"],
    history: {
      zh: "银箭在混合动力时代建立了统治级纪录。2026 年，车队以自研底盘和动力单元进入全新技术周期。",
      en: "The Silver Arrows defined the early hybrid era. In 2026 the works team enters a new technical cycle with its own chassis and power unit.",
    },
  },
  {
    id: "ferrari",
    name: "Ferrari",
    shortName: "Ferrari",
    color: "#e10600",
    base: { zh: "意大利马拉内罗", en: "Maranello, Italy" },
    principal: "Frédéric Vasseur",
    firstEntry: 1950,
    championships: 16,
    points: 307,
    position: 2,
    drivers: ["hamilton", "leclerc"],
    history: {
      zh: "法拉利是唯一参加过每一个 F1 赛季的车队。它把赛车、工程与意大利品牌文化连接成这项运动最鲜明的符号。",
      en: "Ferrari is the only team to have contested every F1 season, uniting racing, engineering and Italian identity into the sport's most enduring symbol.",
    },
  },
  {
    id: "mclaren",
    name: "McLaren",
    shortName: "McLaren",
    color: "#ff8700",
    base: { zh: "英国沃金", en: "Woking, United Kingdom" },
    principal: "Andrea Stella",
    firstEntry: 1966,
    championships: 10,
    points: 220,
    position: 3,
    drivers: ["norris", "piastri"],
    history: {
      zh: "由布鲁斯·迈凯伦创立的车队拥有跨越多个时代的冠军传统，并以快速迭代和高效运营重回争冠行列。",
      en: "Founded by Bruce McLaren, the team carries a championship tradition across eras and returned to the front through rapid development and efficient operations.",
    },
  },
  {
    id: "red-bull",
    name: "Red Bull Racing",
    shortName: "Red Bull",
    color: "#3671c6",
    base: { zh: "英国米尔顿凯恩斯", en: "Milton Keynes, United Kingdom" },
    principal: "Laurent Mekies",
    firstEntry: 2005,
    championships: 6,
    points: 177,
    position: 4,
    drivers: ["verstappen", "hadjar"],
    history: {
      zh: "红牛从挑战者成长为多届世界冠军。2026 年是车队首次使用自有 Red Bull Ford 动力单元的赛季。",
      en: "Red Bull evolved from challenger to multiple world champion. The 2026 season introduces its first Red Bull Ford works power unit.",
    },
  },
  {
    id: "alpine",
    name: "Alpine",
    shortName: "Alpine",
    color: "#2293d1",
    base: { zh: "英国恩斯通", en: "Enstone, United Kingdom" },
    principal: "Steve Nielsen",
    firstEntry: 1986,
    championships: 2,
    points: 61,
    position: 6,
    drivers: ["gasly", "colapinto"],
    history: {
      zh: "恩斯通车队经历过贝纳通、雷诺与 Alpine 等身份，并赢得过车手与车队双冠。2026 年开始采用梅赛德斯动力。",
      en: "The Enstone lineage has raced as Benetton, Renault and Alpine, winning both titles. It moved to Mercedes power for 2026.",
    },
  },
  {
    id: "racing-bulls",
    name: "Racing Bulls",
    shortName: "Racing Bulls",
    color: "#6692ff",
    base: { zh: "意大利法恩扎", en: "Faenza, Italy" },
    principal: "Alan Permane",
    firstEntry: 1985,
    championships: 0,
    points: 66,
    position: 5,
    drivers: ["lawson", "lindblad"],
    history: {
      zh: "车队源自米纳尔迪，长期承担红牛年轻车手培养角色，同时保有独立制造与比赛团队。",
      en: "Born from Minardi, the Faenza team has long developed Red Bull talent while retaining its own racing and manufacturing operation.",
    },
  },
  {
    id: "haas",
    name: "Haas F1 Team",
    shortName: "Haas",
    color: "#b6babd",
    base: { zh: "美国坎纳波利斯", en: "Kannapolis, United States" },
    principal: "Ayao Komatsu",
    firstEntry: 2016,
    championships: 0,
    points: 21,
    position: 7,
    drivers: ["bearman", "ocon"],
    history: {
      zh: "Haas 是 2016 年加入 F1 的美国车队，以跨国运营和技术合作模式挑战传统制造体系。",
      en: "Haas joined F1 in 2016, using a cross-border operating model and technical partnerships to challenge the traditional constructor structure.",
    },
  },
  {
    id: "williams",
    name: "Williams",
    shortName: "Williams",
    color: "#64c4ff",
    base: { zh: "英国格罗夫", en: "Grove, United Kingdom" },
    principal: "James Vowles",
    firstEntry: 1978,
    championships: 9,
    points: 11,
    position: 9,
    drivers: ["sainz", "albon"],
    history: {
      zh: "威廉姆斯是 F1 最成功的独立车队之一，九次获得车队冠军，现正进行长期基础设施与竞技重建。",
      en: "Williams is one of F1's most successful independent teams, with nine constructors' titles and a long-term competitive rebuild under way.",
    },
  },
  {
    id: "audi",
    name: "Audi",
    shortName: "Audi",
    color: "#f50537",
    base: { zh: "瑞士欣维尔", en: "Hinwil, Switzerland" },
    principal: "Jonathan Wheatley",
    firstEntry: 1993,
    championships: 0,
    points: 12,
    position: 8,
    drivers: ["bortoleto", "hulkenberg"],
    history: {
      zh: "Audi 在 2026 年接管索伯席位并以完整厂队身份参赛，底盘在欣维尔研发，动力单元来自德国诺伊堡。",
      en: "Audi took over the Sauber entry in 2026 as a full works operation, developing the chassis in Hinwil and the power unit in Neuburg.",
    },
  },
  {
    id: "aston-martin",
    name: "Aston Martin",
    shortName: "Aston Martin",
    color: "#358c75",
    base: { zh: "英国银石", en: "Silverstone, United Kingdom" },
    principal: "Adrian Newey",
    firstEntry: 2018,
    championships: 0,
    points: 1,
    position: 10,
    drivers: ["alonso", "stroll"],
    history: {
      zh: "车队由前 Force India/Racing Point 体系演变而来，并通过新园区、风洞与本田厂商动力向完整厂队转型。",
      en: "Evolving from the Force India/Racing Point lineage, the team is becoming a full works operation through a new campus, wind tunnel and Honda power.",
    },
  },
  {
    id: "cadillac",
    name: "Cadillac",
    shortName: "Cadillac",
    color: "#b9a779",
    base: { zh: "英国银石 / 美国印第安纳", en: "Silverstone / Indiana" },
    principal: "Graeme Lowdon",
    firstEntry: 2026,
    championships: 0,
    points: 0,
    position: 11,
    drivers: ["bottas", "perez"],
    history: {
      zh: "Cadillac 在 2026 年成为第 11 支车队，初期采用法拉利动力，并计划在 2029 年引入通用汽车自研动力单元。",
      en: "Cadillac became the 11th team in 2026, initially using Ferrari power before a planned General Motors works unit from 2029.",
    },
  },
];

teams.sort((left, right) => left.position - right.position);

const driver = (
  id: string,
  firstName: string,
  lastName: string,
  code: string,
  number: number,
  countryCode: string,
  nationality: [string, string],
  teamId: string,
  points: number,
  position: number,
  championships: number,
  debut: number,
  profile: [string, string],
): Driver => ({
  id,
  firstName,
  lastName,
  code,
  number,
  countryCode,
  nationality: { zh: nationality[0], en: nationality[1] },
  teamId,
  points,
  position,
  championships,
  debut,
  profile: { zh: profile[0], en: profile[1] },
});

export const drivers: Driver[] = [
  driver("antonelli", "Kimi", "Antonelli", "ANT", 12, "IT", ["意大利", "Italian"], "mercedes", 219, 1, 0, 2025, ["以出色的适应力与速度进入争冠行列的梅赛德斯新生代车手。", "Mercedes' young contender has combined rapid adaptation with front-running pace."]),
  driver("russell", "George", "Russell", "RUS", 63, "GB", ["英国", "British"], "mercedes", 160, 3, 0, 2019, ["稳定、精确且擅长技术反馈，是梅赛德斯新时代的核心。", "Consistent, precise and technically articulate, Russell is central to Mercedes' next era."]),
  driver("hamilton", "Lewis", "Hamilton", "HAM", 44, "GB", ["英国", "British"], "ferrari", 169, 2, 7, 2007, ["七届世界冠军，以纪录、比赛能力和赛场外影响力定义了一个时代。", "A seven-time champion whose records, racecraft and off-track influence helped define an era."]),
  driver("leclerc", "Charles", "Leclerc", "LEC", 16, "MC", ["摩纳哥", "Monegasque"], "ferrari", 138, 4, 0, 2018, ["以单圈速度、刹车控制和对法拉利的长期承诺著称。", "Known for qualifying speed, braking control and a long-term commitment to Ferrari."]),
  driver("norris", "Lando", "Norris", "NOR", 1, "GB", ["英国", "British"], "mclaren", 128, 5, 1, 2019, ["2025 世界冠军，拥有流畅速度、轮胎管理与现代车手沟通风格。", "The 2025 World Champion blends fluid pace, tyre management and a modern communication style."]),
  driver("piastri", "Oscar", "Piastri", "PIA", 81, "AU", ["澳大利亚", "Australian"], "mclaren", 92, 7, 0, 2023, ["冷静、高效，职业生涯初期便展现出顶尖比赛执行力。", "Calm and efficient, Piastri showed elite race execution from the beginning of his F1 career."]),
  driver("verstappen", "Max", "Verstappen", "VER", 3, "NL", ["荷兰", "Dutch"], "red-bull", 109, 6, 4, 2015, ["四届世界冠军，以极限控制、雨战能力与持续高强度输出闻名。", "A four-time champion renowned for car control, wet-weather ability and relentless intensity."]),
  driver("hadjar", "Isack", "Hadjar", "HAD", 6, "FR", ["法国", "French"], "red-bull", 68, 8, 0, 2025, ["从 Racing Bulls 晋升红牛，以果断进攻和快速学习赢得机会。", "Promoted from Racing Bulls after earning attention through decisive racing and fast learning."]),
  driver("gasly", "Pierre", "Gasly", "GAS", 10, "FR", ["法国", "French"], "alpine", 42, 10, 0, 2017, ["大奖赛冠军，擅长把握复杂比赛与有限赛车窗口。", "A Grand Prix winner skilled at extracting results from complex races and narrow car windows."]),
  driver("lawson", "Liam", "Lawson", "LAW", 30, "NZ", ["新西兰", "New Zealander"], "racing-bulls", 43, 9, 0, 2023, ["以适应不同赛车和直接的比赛风格建立声誉。", "Built his reputation through adaptability across machinery and a direct racing style."]),
  driver("lindblad", "Arvid", "Lindblad", "LIN", 41, "GB", ["英国", "British"], "racing-bulls", 23, 11, 0, 2026, ["2026 新秀，是红牛青训体系中备受关注的新一代车手。", "The 2026 rookie is one of the most closely watched graduates of Red Bull's junior system."]),
  driver("bearman", "Oliver", "Bearman", "BEA", 87, "GB", ["英国", "British"], "haas", 18, 13, 0, 2024, ["年轻、果断，并在替补出场与首个完整赛季中迅速证明速度。", "Young and decisive, Bearman quickly demonstrated pace in substitute appearances and his first full season."]),
  driver("colapinto", "Franco", "Colapinto", "COL", 43, "AR", ["阿根廷", "Argentine"], "alpine", 19, 12, 0, 2024, ["阿根廷车手，以勇敢的超车判断和强烈的公众号召力受到关注。", "The Argentine attracted attention through bold overtaking judgement and strong public appeal."]),
  driver("bortoleto", "Gabriel", "Bortoleto", "BOR", 5, "BR", ["巴西", "Brazilian"], "audi", 10, 14, 0, 2025, ["连续赢得青年方程式重要锦标后进入 F1，驾驶风格成熟克制。", "Entered F1 after consecutive major junior titles, bringing a mature and measured driving style."]),
  driver("sainz", "Carlos", "Sainz", "SAI", 55, "ES", ["西班牙", "Spanish"], "williams", 6, 15, 0, 2015, ["多站冠军，以完整技术反馈、策略意识和适应力著称。", "A multiple race winner known for complete technical feedback, strategy awareness and adaptability."]),
  driver("albon", "Alexander", "Albon", "ALB", 23, "TH", ["泰国", "Thai"], "williams", 5, 16, 0, 2019, ["擅长防守和管理不稳定的赛车平台，是威廉姆斯重建的重要基准。", "A skilled defender and manager of difficult cars, Albon is a key benchmark in Williams' rebuild."]),
  driver("ocon", "Esteban", "Ocon", "OCO", 31, "FR", ["法国", "French"], "haas", 3, 17, 0, 2016, ["大奖赛冠军，以坚韧、防守与混乱比赛中的执行力见长。", "A Grand Prix winner valued for resilience, defence and execution in unpredictable races."]),
  driver("alonso", "Fernando", "Alonso", "ALO", 14, "ES", ["西班牙", "Spanish"], "aston-martin", 1, 19, 2, 2001, ["两届世界冠军，以比赛阅读、长寿和全能驾驶能力闻名。", "A two-time champion celebrated for race reading, longevity and broad driving ability."]),
  driver("hulkenberg", "Nico", "Hülkenberg", "HUL", 27, "DE", ["德国", "German"], "audi", 2, 18, 0, 2010, ["经验丰富的技术型车手，是 Audi 厂队计划的重要开发基准。", "An experienced technical driver and an important development reference for Audi's works programme."]),
  driver("bottas", "Valtteri", "Bottas", "BOT", 77, "FI", ["芬兰", "Finnish"], "cadillac", 0, 20, 0, 2013, ["十次大奖赛冠军，带着顶级车队经验参与 Cadillac 的首个赛季。", "A ten-time Grand Prix winner bringing front-running experience to Cadillac's debut season."]),
  driver("perez", "Sergio", "Pérez", "PER", 11, "MX", ["墨西哥", "Mexican"], "cadillac", 0, 21, 0, 2011, ["多站冠军，以轮胎管理、街道赛表现与逆境恢复能力著称。", "A multiple winner known for tyre management, street-circuit performance and recovery drives."]),
  driver("stroll", "Lance", "Stroll", "STR", 18, "CA", ["加拿大", "Canadian"], "aston-martin", 0, 22, 0, 2017, ["领奖台车手，在低抓地力和多变天气中曾多次取得突出结果。", "A podium finisher who has often produced his strongest results in low grip and changing weather."]),
];

drivers.sort((left, right) => left.position - right.position);

const car = (
  teamId: string,
  chassis: string,
  powerUnit: string,
  overview: [string, string],
): Car => ({
  id: `${teamId}-2026`,
  season: 2026,
  teamId,
  chassis,
  powerUnit,
  gearbox: "8-speed semi-automatic + reverse",
  fuel: "100% advanced sustainable fuel",
  tyres: "Pirelli 18-inch",
  weight: "768 kg minimum regulatory mass",
  length: "Not disclosed by team",
  width: "1,900 mm maximum",
  wheelbase: "3,400 mm maximum",
  electricalOutput: "350 kW MGU-K regulatory maximum",
  overview: { zh: overview[0], en: overview[1] },
});

export const cars: Car[] = [
  car("mercedes", "Mercedes-AMG F1 W17 E PERFORMANCE", "Mercedes", ["W17 是梅赛德斯针对 2026 全新底盘与动力单元规则打造的一体化厂队方案。", "The W17 is Mercedes' integrated works response to the new 2026 chassis and power-unit rules."]),
  car("ferrari", "Ferrari SF-26", "Ferrari", ["SF-26 在马拉内罗完成底盘与动力单元整合，采用更紧凑的 2026 车身尺寸与主动空气动力学。", "The SF-26 integrates Ferrari chassis and power-unit development around the smaller 2026 dimensions and active aerodynamics."]),
  car("mclaren", "McLaren MCL40", "Mercedes", ["MCL40 延续迈凯伦高效底盘开发模式，并使用梅赛德斯客户动力单元。", "The MCL40 continues McLaren's efficient chassis-development model with a Mercedes customer power unit."]),
  car("red-bull", "Red Bull RB22", "Red Bull Ford", ["RB22 是红牛首台搭载 Red Bull Ford Powertrains 厂商动力单元的 F1 赛车。", "The RB22 is Red Bull's first F1 car powered by its Red Bull Ford works unit."]),
  car("alpine", "Alpine A526", "Mercedes", ["A526 标志 Alpine 从雷诺动力转向梅赛德斯动力与变速箱的技术重启。", "The A526 marks Alpine's technical reset with Mercedes power and transmission hardware."]),
  car("racing-bulls", "Racing Bulls VCARB 03", "Red Bull Ford", ["VCARB 03 共享红牛动力生态，同时由法恩扎团队独立开发底盘。", "The VCARB 03 shares Red Bull's power ecosystem while retaining a Faenza-developed chassis."]),
  car("haas", "Haas VF-26", "Ferrari", ["VF-26 延续 Haas 与法拉利的动力及技术合作模式，重点在有限资源下提高开发效率。", "The VF-26 continues Haas' Ferrari power and technical partnership with an emphasis on efficient development."]),
  car("williams", "Williams FW48", "Mercedes", ["FW48 是威廉姆斯长期技术重建中的首台 2026 规则赛车，使用梅赛德斯动力。", "The FW48 is Williams' first car for the 2026 rules within its long-term technical rebuild, powered by Mercedes."]),
  car("audi", "Audi R26", "Audi", ["R26 是 Audi 首台完整厂队 F1 赛车，底盘与动力单元由同一制造商计划协同开发。", "The R26 is Audi's first full works F1 car, uniting chassis and power-unit development within one manufacturer programme."]),
  car("aston-martin", "Aston Martin AMR26", "Honda", ["AMR26 是车队首台 Adrian Newey 主导、并与本田厂商动力深度整合的 2026 赛车。", "The AMR26 is the team's first 2026 car led by Adrian Newey and deeply integrated with Honda works power."]),
  car("cadillac", "Cadillac MAC-26", "Ferrari", ["MAC-26 是 Cadillac 的首台 F1 赛车，初期使用法拉利动力，为未来通用汽车厂商动力计划建立基础。", "The MAC-26 is Cadillac's debut F1 car, initially Ferrari-powered while the team builds toward a future GM works unit."]),
];

const carImages: Record<string, string> = {
  "mercedes-2026": "/images/mercedes-w17.jpg",
  "ferrari-2026": "/images/ferrari-sf26.jpg",
  "mclaren-2026": "/images/mclaren-mcl40.jpg",
  "red-bull-2026": "/images/red-bull-rb22.jpg",
  "alpine-2026": "/images/alpine-a526.jpg",
  "racing-bulls-2026": "/images/racing-bulls-vcarb03.jpg",
  "haas-2026": "/images/haas-vf26.jpg",
  "williams-2026": "/images/williams-fw48.jpg",
  "audi-2026": "/images/audi-r26.jpg",
  "aston-martin-2026": "/images/aston-martin-amr26.jpg",
  "cadillac-2026": "/images/cadillac-mac26.jpg",
};
const carStudioImages: Record<string, string> = {
  "mercedes-2026": "/images/studio/mercedes-w17-studio.png",
  "ferrari-2026": "/images/studio/ferrari-sf26-studio.png",
  "mclaren-2026": "/images/studio/mclaren-mcl40-studio.png",
  "red-bull-2026": "/images/studio/red-bull-rb22-studio.png",
  "alpine-2026": "/images/studio/alpine-a526-studio.png",
  "racing-bulls-2026": "/images/studio/racing-bulls-vcarb03-studio.png",
  "haas-2026": "/images/studio/haas-vf26-studio.png",
  "williams-2026": "/images/studio/williams-fw48-studio.png",
  "audi-2026": "/images/studio/audi-r26-studio.png",
  "aston-martin-2026": "/images/studio/aston-martin-amr26-studio.png",
  "cadillac-2026": "/images/studio/cadillac-mac26-studio.png",
};
for (const carItem of cars) {
  carItem.image = carImages[carItem.id];
  carItem.studioImage = carStudioImages[carItem.id];
}

const circuit = (
  id: string,
  name: string,
  grandPrix: [string, string],
  city: [string, string],
  country: [string, string],
  countryCode: string,
  lengthKm: number | undefined,
  laps: number | undefined,
  corners: number | undefined,
  firstGrandPrix: number | undefined,
  lapRecord: string | undefined,
  lapRecordHolder: string | undefined,
  character: [string, string],
): Circuit => ({
  id,
  name,
  grandPrix: { zh: grandPrix[0], en: grandPrix[1] },
  city: { zh: city[0], en: city[1] },
  country: { zh: country[0], en: country[1] },
  countryCode,
  lengthKm,
  laps,
  corners,
  raceDistanceKm: lengthKm && laps ? Number((lengthKm * laps).toFixed(3)) : undefined,
  firstGrandPrix,
  lapRecord,
  lapRecordHolder,
  character: { zh: character[0], en: character[1] },
});

export const circuits: Circuit[] = [
  circuit("albert-park", "Albert Park Grand Prix Circuit", ["澳大利亚大奖赛", "Australian Grand Prix"], ["墨尔本", "Melbourne"], ["澳大利亚", "Australia"], "AU", 5.278, 58, 14, 1996, "1:19.813", "Charles Leclerc · 2024", ["半永久街道赛道，路面持续进化，高速变向与重刹车并存。", "A semi-permanent circuit with evolving grip, fast direction changes and heavy braking zones."]),
  circuit("shanghai", "Shanghai International Circuit", ["中国大奖赛", "Chinese Grand Prix"], ["上海", "Shanghai"], ["中国", "China"], "CN", 5.451, 56, 16, 2004, "1:32.238", "Michael Schumacher · 2004", ["标志性的‘上’字布局包含超长 1 号弯和长直道，对前胎与牵引力要求很高。", "Its character-shaped layout combines a tightening first corner and long straight, stressing front tyres and traction."]),
  circuit("suzuka", "Suzuka International Racing Course", ["日本大奖赛", "Japanese Grand Prix"], ["铃鹿", "Suzuka"], ["日本", "Japan"], "JP", 5.807, 53, 18, 1987, "1:30.983", "Lewis Hamilton · 2019", ["F1 唯一的八字形赛道，以连续 S 弯、Degner 与 130R 检验空气动力效率和车手节奏。", "F1's only figure-eight layout tests aerodynamic confidence and rhythm through the Esses, Degner and 130R."]),
  circuit("miami", "Miami International Autodrome", ["迈阿密大奖赛", "Miami Grand Prix"], ["迈阿密花园", "Miami Gardens"], ["美国", "United States"], "US", 5.412, 57, 19, 2022, "1:29.708", "Max Verstappen · 2023", ["围绕硬石体育场搭建的临时赛道，结合高速区、长直道和低速技术段。", "A temporary stadium circuit mixing fast sections, long straights and a tight technical complex."]),
  circuit("gilles-villeneuve", "Circuit Gilles-Villeneuve", ["加拿大大奖赛", "Canadian Grand Prix"], ["蒙特利尔", "Montréal"], ["加拿大", "Canada"], "CA", 4.361, 70, 14, 1978, "1:13.078", "Valtteri Bottas · 2019", ["低下压力、高刹车负荷的停走型赛道，防撞墙距离近，安全车概率高。", "A low-downforce stop-start circuit with heavy braking, nearby walls and frequent safety-car risk."]),
  circuit("monaco", "Circuit de Monaco", ["摩纳哥大奖赛", "Monaco Grand Prix"], ["蒙特卡洛", "Monte Carlo"], ["摩纳哥", "Monaco"], "MC", 3.337, 78, 19, 1950, "1:12.909", "Lewis Hamilton · 2021", ["极窄街道、盲弯和高度变化让排位精度与机械抓地力成为核心。", "Narrow streets, blind corners and elevation changes make qualifying precision and mechanical grip decisive."]),
  circuit("barcelona", "Circuit de Barcelona-Catalunya", ["巴塞罗那-加泰罗尼亚大奖赛", "Barcelona-Catalunya Grand Prix"], ["蒙特梅洛", "Montmeló"], ["西班牙", "Spain"], "ES", 4.657, 66, 14, 1991, "1:16.330", "Max Verstappen · 2023", ["高速、中速与长弯组合完整，是评估整车空气动力学平衡的传统基准。", "A complete mix of fast, medium and long corners makes it a traditional aerodynamic benchmark."]),
  circuit("red-bull-ring", "Red Bull Ring", ["奥地利大奖赛", "Austrian Grand Prix"], ["施皮尔贝格", "Spielberg"], ["奥地利", "Austria"], "AT", 4.318, 71, 10, 1970, "1:05.619", "Carlos Sainz · 2020", ["单圈短、坡度大，三段连续上坡重刹车创造大量攻防机会。", "A short, steep lap with three uphill braking zones that repeatedly creates overtaking opportunities."]),
  circuit("silverstone", "Silverstone Circuit", ["英国大奖赛", "British Grand Prix"], ["银石", "Silverstone"], ["英国", "United Kingdom"], "GB", 5.891, 52, 18, 1950, "1:27.097", "Max Verstappen · 2020", ["高速弯占比极高，Maggotts–Becketts 序列是空气动力性能和车手承诺度的标尺。", "High-speed corners dominate, with Maggotts–Becketts a defining test of aero performance and driver commitment."]),
  circuit("spa", "Circuit de Spa-Francorchamps", ["比利时大奖赛", "Belgian Grand Prix"], ["斯塔沃洛", "Stavelot"], ["比利时", "Belgium"], "BE", 7.004, 44, 19, 1950, "1:46.286", "Valtteri Bottas · 2018", ["全季最长赛道，天气可能分区变化；Eau Rouge、Raidillon 与长直道要求兼顾低阻力和高速稳定。", "The season's longest lap can have localised weather; Eau Rouge, Raidillon and long straights demand low drag and high-speed stability."]),
  circuit("hungaroring", "Hungaroring", ["匈牙利大奖赛", "Hungarian Grand Prix"], ["莫焦罗德", "Mogyoród"], ["匈牙利", "Hungary"], "HU", 4.381, 70, 14, 1986, "1:16.627", "Lewis Hamilton · 2020", ["连续中低速弯让赛道像没有护墙的摩纳哥，超车困难且节奏非常重要。", "A linked sequence of medium- and low-speed corners rewards rhythm and makes overtaking difficult."]),
  circuit("zandvoort", "Circuit Zandvoort", ["荷兰大奖赛", "Dutch Grand Prix"], ["赞德沃特", "Zandvoort"], ["荷兰", "Netherlands"], "NL", 4.259, 72, 14, 1952, "1:11.097", "Lewis Hamilton · 2021", ["沙丘间的窄赛道拥有大坡度弯，横风和砂砾会改变抓地力。", "A narrow dune circuit with steep banking, crosswinds and sand that can alter grip."]),
  circuit("monza", "Autodromo Nazionale Monza", ["意大利大奖赛", "Italian Grand Prix"], ["蒙扎", "Monza"], ["意大利", "Italy"], "IT", 5.793, 53, 11, 1950, "1:21.046", "Rubens Barrichello · 2004", ["‘速度圣殿’以超长全油门比例和重刹车减速弯定义最低下压力设定。", "The Temple of Speed combines extended full-throttle running with heavy-braking chicanes and minimum downforce."]),
  circuit("madrid", "Madring", ["西班牙大奖赛", "Spanish Grand Prix"], ["马德里", "Madrid"], ["西班牙", "Spain"], "ES", undefined, undefined, undefined, 2026, undefined, undefined, ["2026 新赛道；最终比赛长度、圈数与纪录需以 FIA 认证和正式周末文件为准。", "A new 2026 venue; final length, lap count and records remain subject to FIA homologation and official event documents."]),
  circuit("baku", "Baku City Circuit", ["阿塞拜疆大奖赛", "Azerbaijan Grand Prix"], ["巴库", "Baku"], ["阿塞拜疆", "Azerbaijan"], "AZ", 6.003, 51, 20, 2016, "1:43.009", "Charles Leclerc · 2019", ["古城极窄路段与全季最长直道之一形成极端反差，尾流和安全车可彻底改变比赛。", "An ultra-tight old-city section contrasts with one of the longest straights, making slipstream and safety cars decisive."]),
  circuit("sepang", "Sepang International Circuit", ["马来西亚巴林大奖赛", "Bahrain Grand Prix in Malaysia"], ["雪邦", "Sepang"], ["马来西亚", "Malaysia"], "MY", undefined, undefined, undefined, 1999, undefined, undefined, ["2026 年 10 月的替代赛事已由 Formula 1 与 FIA 公布；最终比赛参数以正式周末文件为准。", "Formula 1 and the FIA announced this replacement event for October 2026; final race parameters remain subject to official event documents."]),
  circuit("marina-bay", "Marina Bay Street Circuit", ["新加坡大奖赛", "Singapore Grand Prix"], ["新加坡", "Singapore"], ["新加坡", "Singapore"], "SG", 4.94, 62, 19, 2008, "1:35.867", "Lewis Hamilton · 2023", ["高温、高湿与密集刹车的夜间街道赛，对体能、散热和轮胎控制要求极高。", "A hot, humid night street race with relentless braking demands physical fitness, cooling and tyre control."]),
  circuit("cota", "Circuit of the Americas", ["美国大奖赛", "United States Grand Prix"], ["奥斯汀", "Austin"], ["美国", "United States"], "US", 5.513, 56, 20, 2012, "1:36.169", "Charles Leclerc · 2019", ["大上坡 1 号弯、快速连续弯和长直道组成完整的现代赛道考题。", "A steep Turn 1, fast esses and long back straight create a complete modern circuit test."]),
  circuit("mexico-city", "Autódromo Hermanos Rodríguez", ["墨西哥城大奖赛", "Mexico City Grand Prix"], ["墨西哥城", "Mexico City"], ["墨西哥", "Mexico"], "MX", 4.304, 71, 17, 1963, "1:17.774", "Valtteri Bottas · 2021", ["高海拔稀薄空气削弱下压力和冷却效率，即使高翼设定也呈现极高直线速度。", "Thin high-altitude air reduces downforce and cooling, producing high straight-line speed even with large wings."]),
  circuit("interlagos", "Autódromo José Carlos Pace", ["圣保罗大奖赛", "São Paulo Grand Prix"], ["圣保罗", "São Paulo"], ["巴西", "Brazil"], "BR", 4.309, 71, 15, 1973, "1:10.540", "Valtteri Bottas · 2018", ["逆时针、起伏大且天气多变，短单圈经常制造密集车流和策略反转。", "An undulating anti-clockwise lap with volatile weather often produces traffic compression and strategy reversals."]),
  circuit("las-vegas", "Las Vegas Strip Circuit", ["拉斯维加斯大奖赛", "Las Vegas Grand Prix"], ["拉斯维加斯", "Las Vegas"], ["美国", "United States"], "US", 6.201, 50, 17, 2023, "1:35.490", "Oscar Piastri · 2023", ["夜间低温与极长直道让轮胎升温、低阻力和刹车稳定成为核心。", "Cold night temperatures and long straights make tyre warm-up, low drag and braking stability central."]),
  circuit("lusail", "Lusail International Circuit", ["卡塔尔大奖赛", "Qatar Grand Prix"], ["卢赛尔", "Lusail"], ["卡塔尔", "Qatar"], "QA", 5.419, 57, 16, 2021, "1:24.319", "Max Verstappen · 2023", ["快速流动弯道和高横向载荷持续考验轮胎结构与车手体能。", "Fast, flowing corners and sustained lateral load place exceptional stress on tyres and drivers."]),
  circuit("yas-marina", "Yas Marina Circuit", ["阿布扎比大奖赛", "Abu Dhabi Grand Prix"], ["阿布扎比", "Abu Dhabi"], ["阿联酋", "United Arab Emirates"], "AE", 5.281, 58, 16, 2009, "1:26.103", "Max Verstappen · 2021", ["黄昏收官战从日光进入夜间，长直道与技术性末段要求均衡设定。", "The twilight finale transitions from daylight to night, combining long straights with a technical final sector."]),
];

const podium = (
  first: [string, string, string, string],
  second: [string, string, string, string],
  third: [string, string, string, string],
): NonNullable<Race["podium"]> => [
  { position: 1, driverId: first[0], driverName: first[1], teamName: first[2], time: first[3] },
  { position: 2, driverId: second[0], driverName: second[1], teamName: second[2], time: second[3] },
  { position: 3, driverId: third[0], driverName: third[1], teamName: third[2], time: third[3] },
];

const race = (
  round: number,
  circuitId: string,
  name: [string, string],
  countryCode: string,
  startDate: string,
  endDate: string,
  result?: NonNullable<Race["podium"]>,
  sprint = false,
  id = `${CURRENT_SEASON}-${circuitId}`,
  confirmation: Race["confirmation"] = "confirmed",
): Race => ({
  id,
  season: CURRENT_SEASON,
  round,
  circuitId,
  name: { zh: name[0], en: name[1] },
  countryCode,
  startDate,
  endDate,
  status: raceStatusFor({ startDate, endDate, classificationPublished: Boolean(result) }),
  sprint,
  confirmation,
  winner: result?.[0].driverId,
  winningTime: result?.[0].time,
  podium: result,
});

export const races2026: Race[] = [
  race(1, "albert-park", ["澳大利亚大奖赛", "Australian Grand Prix"], "AU", "2026-03-06", "2026-03-08", podium(["russell", "George Russell", "Mercedes", "1:23:06.801"], ["antonelli", "Kimi Antonelli", "Mercedes", "+2.974"], ["leclerc", "Charles Leclerc", "Ferrari", "+15.519"])),
  race(2, "shanghai", ["中国大奖赛", "Chinese Grand Prix"], "CN", "2026-03-13", "2026-03-15", podium(["antonelli", "Kimi Antonelli", "Mercedes", "1:33:15.607"], ["russell", "George Russell", "Mercedes", "+5.515"], ["hamilton", "Lewis Hamilton", "Ferrari", "+25.267"]), true),
  race(3, "suzuka", ["日本大奖赛", "Japanese Grand Prix"], "JP", "2026-03-27", "2026-03-29", podium(["antonelli", "Kimi Antonelli", "Mercedes", "1:28:03.403"], ["piastri", "Oscar Piastri", "McLaren", "+13.722"], ["leclerc", "Charles Leclerc", "Ferrari", "+15.270"])),
  race(4, "miami", ["迈阿密大奖赛", "Miami Grand Prix"], "US", "2026-05-01", "2026-05-03", podium(["antonelli", "Kimi Antonelli", "Mercedes", "1:33:19.273"], ["norris", "Lando Norris", "McLaren", "+3.264"], ["piastri", "Oscar Piastri", "McLaren", "+27.092"]), true),
  race(5, "gilles-villeneuve", ["加拿大大奖赛", "Canadian Grand Prix"], "CA", "2026-05-22", "2026-05-24", podium(["antonelli", "Kimi Antonelli", "Mercedes", "1:28:15.758"], ["hamilton", "Lewis Hamilton", "Ferrari", "+10.768"], ["verstappen", "Max Verstappen", "Red Bull", "+11.276"]), true),
  race(6, "monaco", ["摩纳哥大奖赛", "Monaco Grand Prix"], "MC", "2026-06-05", "2026-06-07", podium(["antonelli", "Kimi Antonelli", "Mercedes", "2:23:31.243"], ["hamilton", "Lewis Hamilton", "Ferrari", "+6.271"], ["gasly", "Pierre Gasly", "Alpine", "+20.369"])),
  race(7, "barcelona", ["巴塞罗那-加泰罗尼亚大奖赛", "Barcelona-Catalunya Grand Prix"], "ES", "2026-06-12", "2026-06-14", podium(["hamilton", "Lewis Hamilton", "Ferrari", "1:32:28.105"], ["russell", "George Russell", "Mercedes", "+19.561"], ["norris", "Lando Norris", "McLaren", "+23.719"])),
  race(8, "red-bull-ring", ["奥地利大奖赛", "Austrian Grand Prix"], "AT", "2026-06-26", "2026-06-28", podium(["russell", "George Russell", "Mercedes", "1:26:37.979"], ["verstappen", "Max Verstappen", "Red Bull", "+1.611"], ["antonelli", "Kimi Antonelli", "Mercedes", "+1.986"])),
  race(9, "silverstone", ["英国大奖赛", "British Grand Prix"], "GB", "2026-07-03", "2026-07-05", podium(["leclerc", "Charles Leclerc", "Ferrari", "1:27:11.335"], ["russell", "George Russell", "Mercedes", "+0.427"], ["hamilton", "Lewis Hamilton", "Ferrari", "+0.772"]), true),
  race(10, "spa", ["比利时大奖赛", "Belgian Grand Prix"], "BE", "2026-07-17", "2026-07-19", podium(["antonelli", "Kimi Antonelli", "Mercedes", "1:24:42.479"], ["leclerc", "Charles Leclerc", "Ferrari", "+1.952"], ["verstappen", "Max Verstappen", "Red Bull Racing", "+11.586"])),
  race(11, "hungaroring", ["匈牙利大奖赛", "Hungarian Grand Prix"], "HU", "2026-07-24", "2026-07-26", podium(["norris", "Lando Norris", "McLaren", "1:39:56.180"], ["verstappen", "Max Verstappen", "Red Bull Racing", "+15.080"], ["antonelli", "Kimi Antonelli", "Mercedes", "+18.728"])),
  race(12, "zandvoort", ["荷兰大奖赛", "Dutch Grand Prix"], "NL", "2026-08-21", "2026-08-23", undefined, true),
  race(13, "monza", ["意大利大奖赛", "Italian Grand Prix"], "IT", "2026-09-04", "2026-09-06"),
  race(14, "madrid", ["西班牙大奖赛", "Spanish Grand Prix"], "ES", "2026-09-11", "2026-09-13"),
  race(15, "baku", ["阿塞拜疆大奖赛", "Azerbaijan Grand Prix"], "AZ", "2026-09-24", "2026-09-26"),
  race(16, "sepang", ["马来西亚巴林大奖赛", "Bahrain Grand Prix in Malaysia"], "MY", "2026-10-02", "2026-10-04", undefined, false, "2026-bahrain-malaysia-sepang", "provisional"),
  race(17, "marina-bay", ["新加坡大奖赛", "Singapore Grand Prix"], "SG", "2026-10-09", "2026-10-11", undefined, true),
  race(18, "cota", ["美国大奖赛", "United States Grand Prix"], "US", "2026-10-23", "2026-10-25"),
  race(19, "mexico-city", ["墨西哥城大奖赛", "Mexico City Grand Prix"], "MX", "2026-10-30", "2026-11-01"),
  race(20, "interlagos", ["圣保罗大奖赛", "São Paulo Grand Prix"], "BR", "2026-11-06", "2026-11-08"),
  race(21, "las-vegas", ["拉斯维加斯大奖赛", "Las Vegas Grand Prix"], "US", "2026-11-19", "2026-11-21"),
  race(22, "lusail", ["卡塔尔大奖赛", "Qatar Grand Prix"], "QA", "2026-11-27", "2026-11-29"),
  race(23, "yas-marina", ["阿布扎比大奖赛", "Abu Dhabi Grand Prix"], "AE", "2026-12-04", "2026-12-06"),
];

export const news: NewsItem[] = [
  {
    id: "belgium-weekend-2026",
    publishedAt: "2026-07-17",
    expiresAt: "2026-07-20",
    kind: "event-status",
    category: "race",
    publisher: "Formula 1",
    title: { zh: "2026 比利时大奖赛周末进行中", en: "The 2026 Belgian Grand Prix weekend is under way" },
    summary: { zh: "赛季第 10 站来到斯帕。查看官方周末页面获取赛程、最新分类与现场更新。", en: "Round 10 brings the field to Spa. The official event page carries schedules, classifications and weekend updates." },
    url: "https://www.formula1.com/en/racing/2026/belgium",
  },
  {
    id: "british-result-2026",
    publishedAt: "2026-07-05",
    category: "race",
    publisher: "Formula 1",
    title: { zh: "勒克莱尔赢得 2026 英国大奖赛", en: "Leclerc wins the 2026 British Grand Prix" },
    summary: { zh: "法拉利车手在银石率先完赛，拉塞尔与汉密尔顿分列第二、第三。", en: "The Ferrari driver led the classification at Silverstone, ahead of Russell and Hamilton." },
    url: "https://www.formula1.com/en/results/2026/races",
  },
  {
    id: "ferrari-power-unit-austria",
    publishedAt: "2026-06-25",
    category: "technical",
    publisher: "Formula 1",
    title: { zh: "法拉利确认奥地利站动力单元升级", en: "Ferrari confirms power-unit update for Austria" },
    summary: { zh: "升级属于 2026 年追加开发机会的一部分，配合车身更新扩大工作窗口。", en: "The change forms part of 2026 additional development opportunities and follows a significant car update." },
    url: "https://www.formula1.com/en/latest/article/ferrari-confirm-power-unit-update-for-austrian-grand-prix-weekend.3uc4ZjUfz5O75zc7lonna1",
  },
  {
    id: "new-era-2026",
    publishedAt: "2026-02-28",
    category: "technical",
    publisher: "FIA",
    title: { zh: "FIA 继续细化 2026 技术规则", en: "FIA continues to refine the 2026 technical rules" },
    summary: { zh: "在季前测试反馈后，世界汽车运动理事会批准了一组技术、运动和财务规则修订。", en: "Following pre-season feedback, the World Motor Sport Council approved technical, sporting and financial refinements." },
    url: "https://www.fia.com/news/fia-statement-amendments-2026-f1-regulations",
  },
];
